### ISSUE TITLE
errors in installing correlation_package

### ISSUE THREAD

**Issue by complexfilter** [cattaneod/MaskFlownet-Pytorch#3]
I had errors in installing correlation_package. My PyTorch version 1.5.0. My CUDA version is 10.1. My gcc version is 10.1.0.
```
running install
running bdist_egg
running egg_info
writing correlation_cuda.egg-info\PKG-INFO
writing dependency_links to correlation_cuda.egg-info\dependency_links.txt
writing top-level names to correlation_cuda.egg-info\top_level.txt
reading manifest file 'correlation_cuda.egg-info\SOURCES.txt'
writing manifest file 'correlation_cuda.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
C:\Users\lantaoyu\Miniconda3\lib\site-packages\torch\utils\cpp_extension.py:237: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'correlation_cuda' extension
Emitting ninja build file C:\Users\lantaoyu\Documents\MaskFlownet-Pytorch-master\MaskFlownet-Pytorch-master\model\correlation_package\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\Users\lantaoyu\Miniconda3\lib\site-packages\torch\include -IC:\Users\lantaoyu\Miniconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\lantaoyu\Miniconda3\lib\site-packages\torch\include\TH -IC:\Users\lantaoyu\Miniconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\Users\lantaoyu\Miniconda3\include -IC:\Users\lantaoyu\Miniconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c C:\Users\lantaoyu\Documents\MaskFlownet-Pytorch-master\MaskFlownet-Pytorch-master\model\correlation_package\correlation_cuda.cc /FoC:\Users\lantaoyu\Documents\MaskFlownet-Pytorch-master\MaskFlownet-Pytorch-master\model\correlation_package\build\temp.win-amd64-3.7\Release\correlation_cuda.obj -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=correlation_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: C:/Users/lantaoyu/Documents/MaskFlownet-Pytorch-master/MaskFlownet-Pytorch-master/model/correlation_package/build/temp.win-amd64-3.7/Release/correlation_cuda.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\Users\lantaoyu\Miniconda3\lib\site-packages\torch\include -IC:\Users\lantaoyu\Miniconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\lantaoyu\Miniconda3\lib\site-packages\torch\include\TH -IC:\Users\lantaoyu\Miniconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\Users\lantaoyu\Miniconda3\include -IC:\Users\lantaoyu\Miniconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c C:\Users\lantaoyu\Documents\MaskFlownet-Pytorch-master\MaskFlownet-Pytorch-master\model\correlation_package\correlation_cuda.cc /FoC:\Users\lantaoyu\Documents\MaskFlownet-Pytorch-master\MaskFlownet-Pytorch-master\model\correlation_package\build\temp.win-amd64-3.7\Release\correlation_cuda.obj -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=correlation_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
ninja: fatal: ReadFile: The handle is invalid.

Traceback (most recent call last):
  File "C:\Users\lantaoyu\Miniconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "C:\Users\lantaoyu\Miniconda3\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    'build_ext': BuildExtension
  File "C:\Users\lantaoyu\Miniconda3\lib\site-packages\setuptools\__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\lantaoyu\Miniconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\lantaoyu\Miniconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\lantaoyu\Miniconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\lantaoyu\Miniconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\lantaoyu\Miniconda3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\lantaoyu\Miniconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\lantaoyu\Miniconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\lantaoyu\Miniconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\lantaoyu\Miniconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 159, in call_command
    self.run_command(cmdname)
  File "C:\Users\lantaoyu\Miniconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\lantaoyu\Miniconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\lantaoyu\Miniconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\lantaoyu\Miniconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\lantaoyu\Miniconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\lantaoyu\Miniconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\lantaoyu\Miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "C:\Users\lantaoyu\Miniconda3\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\lantaoyu\Miniconda3\lib\site-packages\torch\utils\cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\lantaoyu\Miniconda3\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\lantaoyu\Miniconda3\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\lantaoyu\Miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\lantaoyu\Miniconda3\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\Users\lantaoyu\Miniconda3\lib\site-packages\torch\utils\cpp_extension.py", line 562, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\lantaoyu\Miniconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\lantaoyu\Miniconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
```

**Comment by complexfilter** [comment]
My OS is windows.

**Comment by cattaneod** [comment]
Hi,
I'm not familiar with pytorch on windows.
From this line
```C:\Users\lantaoyu\Miniconda3\lib\site-packages\torch\utils\cpp_extension.py:237: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified```
seems that something is missing from the PATH?

Try to have a look here: https://discuss.pytorch.org/t/error-with-cpp-extentions/67559
